NPL bin dir: /mnt/d/workspace/npl/NPLRuntime/ParaWorld/bin64/
no packages at: /mnt/d/workspace/npl/NPLRuntime/ParaWorld/packages
ParaEngine Root Dir is /mnt/d/workspace/lua/keepwork/
search path: /mnt/d/workspace/npl/NPLRuntime/npl_packages/main/
./packages dir: /mnt/d/workspace/lua/keepwork/
main loop: index.lua 
CAssetManifest loaded 0 files
CAsyncLoader is started with 1 IO thread and 2 worker thread
warning: ParaEngine::LoadLibrary( ./libPhysicsBT.so ) failed because ./libPhysicsBT.so: cannot open shared object file: No such file or directory
Failed loading plug-in: ./libPhysicsBT.so
note: no physics engine found, null physics is used 
2017-10-23 19:38:53|-1562245248|ParaEngineServer started
(main) state is now running in a separate thread. It is more responsive now. 
ParaEngine LuaJIT 64bits version:LuaJIT 2.1.0-beta3
Jit status:true, SSE2, SSE3, SSE4.1, BMI2, fold, cse, dce, fwd, dse, narrow, loop, abc, sink, fuse 
ffi loaded shared lib: C
warning: script file npl_util.lua not found
-----------
{is_start=false,response={},request={},router={handler={groupHandler={},fileHandler={},controllerHandler={},pathHandler={},},},util={},}/root/workspace/lua/keepwork/server/npl_http.luaNPL server 0.1 is listening on 0.0.0.0:88
TCPKeepAlive: false
AppKeepAlive: false
IdleTimeout: true
IdleTimeoutPeriod: 120000
UseCompression(incoming): false
CompressionLevel: -1
CompressionThreshold: 204800
NPL max pending incoming connections allowed is 1000
2017-10-23 19:38:53|-2080438528|incoming connection (127.0.0.1/61945) is established and assigned a temporary id (~1). 
[string "index.lua"]:53: attempt to index local 'resp' (a nil value) <Runtime error>
2017-10-23 19:38:53|-2080438528|incoming connection (127.0.0.1/61946) is established and assigned a temporary id (~2). 
2017-10-23 19:40:55|-2080438528|connection time out (127.0.0.1/61945) with id (~1). 
2017-10-23 19:40:55|-2080438528|connection time out (127.0.0.1/61946) with id (~2). 
2017-10-23 19:40:55|-2080438528|connection closed (127.0.0.1/61945) with id (~1). 
2017-10-23 19:40:55|-2080438528|connection closed (127.0.0.1/61946) with id (~2). 
2017-10-23 19:40:55|-2080438528|incoming connection (127.0.0.1/62127) is established and assigned a temporary id (~3). 
[string "index.lua"]:53: attempt to index local 'resp' (a nil value) <Runtime error>
2017-10-23 19:40:55|-2080438528|incoming connection (127.0.0.1/62128) is established and assigned a temporary id (~4). 
network: handle_read stopped, asio msg: End of file. Connection will be closed 
2017-10-23 19:41:34|-2080438528|connection closed (127.0.0.1/62128) with id (~4). 
network: handle_read stopped, asio msg: End of file. Connection will be closed 
